# Generated by Django 3.2.20 on 2023-09-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_quizoption_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='correct_option',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='QuizOption',
        ),
    ]
