# Generated by Django 3.2.20 on 2023-09-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20230903_1349'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_4',
        ),
    ]
