# Generated by Django 3.2.20 on 2023-09-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20230903_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='correct_option',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_four',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_three',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('topic', 'question_text')},
        ),
    ]
