# Generated by Django 3.2.20 on 2023-09-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20230904_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='option_four',
            new_name='option_1',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='option_one',
            new_name='option_2',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='option_three',
            new_name='option_3',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='option_two',
            new_name='option_4',
        ),
    ]
